export const cases = [
  {
    client: "Banco BV",
    segment: "Financeiro",
    challenge: "Modernização e evolução de plataformas digitais.",
    approach: "Arquitetura de sistemas, desenvolvimento de aplicações e integração de dados.",
    solution: "Sistemas e aplicações web",
    outcome: "Maior visibilidade operacional e base sólida para evolução.",
  },
  {
    client: "Eduzz",
    segment: "Tecnologia / Edtech",
    challenge: "Escalabilidade e estruturação de dados.",
    approach: "Arquitetura de dados e engenharia de pipelines.",
    solution: "Plataforma de dados e analytics",
    outcome: "Melhoria da tomada de decisão e governança de dados.",
  },
  {
    client: "Libert",
    segment: "Seguros",
    challenge: "Transformação digital e operação de dados.",
    approach: "Sistemas sob medida, analytics e integração.",
    solution: "Sistemas e ambientes analíticos",
    outcome: "Ganho de eficiência e arquitetura mais escalável.",
  },
  {
    client: "USP",
    segment: "Educação",
    challenge: "Plataformas e ambientes de dados acadêmicos.",
    approach: "Desenvolvimento de sistemas e arquitetura de dados.",
    solution: "Sistemas e infraestrutura de dados",
    outcome: "Modernização da operação e base confiável para analytics.",
  },
  {
    client: "Beanalityc",
    segment: "Tecnologia",
    challenge: "Produtos de analytics e BI.",
    approach: "Engenharia de dados, visualização e dashboards.",
    solution: "Ambientes analíticos e BI",
    outcome: "Produtos data-driven e maior clareza para decisões.",
  },
  {
    client: "Zummit",
    segment: "Tecnologia",
    challenge: "Plataforma e experiência digital.",
    approach: "Desenvolvimento web e engenharia de produto.",
    solution: "Aplicações web e sistemas",
    outcome: "Produto mais robusto e experiência aprimorada.",
  },
  {
    client: "ArcelorMittal",
    segment: "Indústria",
    challenge: "Estruturação de dados e decisão.",
    approach: "Arquitetura de dados, BI e governança.",
    solution: "Plataforma de dados e analytics",
    outcome: "Melhoria da tomada de decisão e visibilidade operacional.",
  },
  {
    client: "Havan",
    segment: "Varejo",
    challenge: "Operação e visibilidade de dados.",
    approach: "Sistemas, integração e ambientes analíticos.",
    solution: "Sistemas e analytics",
    outcome: "Maior eficiência e base mais confiável para evolução.",
  },
] as const;
